This file will contain instructions on how to import RM2C data into the sm64ex-alo repo.
First you should always copy the exported folders (/src,/levels,/sound,/text,/textures,/actors) into your repo.
Then make sure you set RM2C inside the makefile to 1
Then to build for PC use this input to terminal: "make clean && make -j4 TARGET_N64=0 TARGET_ARCH=native WINDOWS_BUILD=1 TARGET_GAME_CONSOLE=0 DEBUG=1 NODRAWINGDISTANCE=1"
Then to build for N64 use this input to terminal: "make clean && make -j4"
By default, due to their high variability and unique names, no actor data will be included from RM2C output, you must
go per actor and either copy data from a custom.model.inc.c file to the model.inc.c file, or change the includes in group files.

Level specific models will go into a folder inside of /actors/ with the name of the level they belong to. You must copy these folders
over to their level folders. The directory should match the target level dir, and not overwrite any files. Textures should be pre written
to the target level directories.

Below are some warnings generated by RM2C during extraction.
It is expected to have many warnings for editor files and for roms with lots of custom content.

******************************************************************************************
Bhv_Custom_0x130002a0 flipswitch panel star spawner with model
Objects without references must have behaviors created for them, be given an existing behavior, or be commented out.
 Level hmc Area 1 has object  Bhv_Custom_0x130002a0 with no known label.
 Level rr Area 2 has object  Bhv_Custom_0x130002a0 with no known label.
 Level ttm Area 1 has object  Bhv_Custom_0x130002a0 with no known label.
******************************************************************************************

Levels with fog in sm64 editor and likely early versions of Rom Manager are completely broken and destroy the levels graphics and most non opaque objects.
I attempt to auto fix these, if there is any issue in these levels check fog first.

 Level bbh Display List DL_bbh_1_0xe0c85e0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_bbh_1_0xe0ff168 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ccm Display List DL_ccm_1_0xe0cae40 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ccm Display List DL_ccm_1_0xe0ea960 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level hmc Display List DL_hmc_1_0xe07d3c0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level hmc Display List DL_hmc_1_0xe09e738 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_1_0xe05fe30 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_1_0xe0791b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_wdw_1_0xe055340 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_wdw_1_0xe067148 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_1_0xe0ddca0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_1_0xe115f48 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_thi_1_0xe0d3940 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_thi_1_0xe0fd9b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_1_0xe069430 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_1_0xe07da80 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_2_0xe09a760 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_3_0xe0c46b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level rr Display List DL_rr_2_0xe0bd388 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level castle_grounds Display List DL_castle_grounds_1_0xe07b840 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level castle_grounds Display List DL_castle_grounds_1_0xe09c500 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bitfs Display List DL_bitfs_1_0xe07fc90 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bitfs Display List DL_bitfs_1_0xe0a1de0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level sa Display List DL_sa_1_0xe05bac0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level sa Display List DL_sa_1_0xe06f010 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level lll Display List DL_lll_1_0xe0897a0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level lll Display List DL_lll_1_0xe0affa0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ddd Display List DL_ddd_1_0xe057de0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ddd Display List DL_ddd_1_0xe067e20 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wf Display List DL_wf_1_0xe0c7fc0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wf Display List DL_wf_1_0xe0fc910 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_1_0xe082c20 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_1_0xe0a18f8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_2_0xe0e08e0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006880 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006758 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006a88 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006bd0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006d00 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600cfd0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600c8b8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600c468 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600baf8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600dfa8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600c030 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600d440 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600d6d8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600de38 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600da88 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600dc60 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600d8b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_0005A0_0x7022da0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_0005B8_0x7023090 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_0005D0_0x7022aa0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_000548_0x7023bc8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_000570_0x7023e10 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_000588_0x7024110 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_hmc_geo_000530_0x701fff8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_0005D8_0x7004ae0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_000734_0x70220a8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_000734_0x70221e8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_000764_0x70228a8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_000764_0x70229e8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_000794_0x7022cf8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_0007AC_0x70233a8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_ssl_geo_0007AC_0x70235c0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
******************************************************************************************

Texture scrolls do not always follow the same format I assume, if this error appears it may have an invalid address which causes a crash.
RM2C will try to find the correct address after noticing the one it has is wrong, if a crash occurs when entering the level check these objects first

 Texture Scroll Object in level castle_inside area 1 at 0xe0aafc0 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0a9640 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0a8020 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0a6850 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0a00c0 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0ae8f0 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0ad120 likely has a bad address.
 Texture Scroll Object in level castle_inside area 1 at 0xe0ab950 likely has a bad address.
 Texture Scroll Object in level hmc area 1 at 0xe0a6b00 likely has a bad address.
 Texture Scroll Object in level hmc area 1 at 0xe0a5330 likely has a bad address.
 Texture Scroll Object in level hmc area 1 at 0xe0a3b60 likely has a bad address.
 Texture Scroll Object in level hmc area 1 at 0xe0ad0c0 likely has a bad address.
 Texture Scroll Object in level hmc area 1 at 0xe0a0550 likely has a bad address.
 Texture Scroll Object in level hmc area 1 at 0xe0aed80 likely has a bad address.
 Texture Scroll Object in level sl area 1 at 0xe0a24a0 likely has a bad address.
 Texture Scroll Object in level sl area 1 at 0xe0a4d30 likely has a bad address.
 Texture Scroll Object in level sl area 1 at 0xe0a4010 likely has a bad address.
 Texture Scroll Object in level wdw area 1 at 0xe0ab0f0 likely has a bad address.
 Texture Scroll Object in level wdw area 1 at 0xe0ad210 likely has a bad address.
 Texture Scroll Object in level castle_grounds area 1 at 0xe0a9240 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a0b10 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a6660 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a4e90 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a36c0 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0af340 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a2910 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a1f80 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0a07b0 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0aefe0 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0ad810 likely has a bad address.
 Texture Scroll Object in level bitdw area 1 at 0xe0ad630 likely has a bad address.
 Texture Scroll Object in level vcutm area 1 at 0xe0a5f50 likely has a bad address.
 Texture Scroll Object in level bitfs area 1 at 0xe0a8390 likely has a bad address.
 Texture Scroll Object in level bitfs area 1 at 0xe0a83f0 likely has a bad address.
 Texture Scroll Object in level bitfs area 1 at 0xe0aa8c0 likely has a bad address.
 Texture Scroll Object in level bits area 1 at 0xe0ae170 likely has a bad address.
 Texture Scroll Object in level bits area 1 at 0xe0a7410 likely has a bad address.
 Texture Scroll Object in level bits area 1 at 0xe0ad390 likely has a bad address.
 Texture Scroll Object in level bits area 1 at 0xe0ad390 likely has a bad address.
 Texture Scroll Object in level lll area 1 at 0xe0ab970 likely has a bad address.
 Texture Scroll Object in level lll area 1 at 0xe0a9c00 likely has a bad address.
 Texture Scroll Object in level ddd area 1 at 0xe0a7bd0 likely has a bad address.
 Texture Scroll Object in level ddd area 1 at 0xe0a6b70 likely has a bad address.
 Texture Scroll Object in level cotmc area 1 at 0xe0aeb70 likely has a bad address.
 Texture Scroll Object in level cotmc area 1 at 0xe0aac10 likely has a bad address.
 Texture Scroll Object in level cotmc area 1 at 0xe0aabe0 likely has a bad address.
 Texture Scroll Object in level cotmc area 1 at 0xe0a9410 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0aaa10 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0aaa10 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0ac050 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0ad640 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0a0b00 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0af040 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0a27c0 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0a3e40 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0a06c0 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0a8790 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0a6fc0 likely has a bad address.
 Texture Scroll Object in level totwc area 1 at 0xe0ac050 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0a77e0 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0a6010 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0ac1b0 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0a3c90 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0ab630 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0a0400 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0aec30 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0ad460 likely has a bad address.
 Texture Scroll Object in level bowser_1 area 1 at 0xe0abc90 likely has a bad address.
 Texture Scroll Object in level wmotr area 1 at 0xe0a9770 likely has a bad address.
 Texture Scroll Object in level wmotr area 1 at 0xe0a8430 likely has a bad address.
 Texture Scroll Object in level wmotr area 1 at 0xe0a7e60 likely has a bad address.
 Texture Scroll Object in level wmotr area 1 at 0xe0a7e60 likely has a bad address.
 Texture Scroll Object in level wmotr area 1 at 0xe0a61d0 likely has a bad address.
 Texture Scroll Object in level bowser_2 area 1 at 0xe0a2770 likely has a bad address.
 Texture Scroll Object in level bowser_2 area 1 at 0xe0ac070 likely has a bad address.
 Texture Scroll Object in level bowser_2 area 1 at 0xe0a4b70 likely has a bad address.
 Texture Scroll Object in level bowser_3 area 1 at 0xe059110 likely has a bad address.
 Texture Scroll Object in level bowser_3 area 1 at 0xe054010 likely has a bad address.

Known methods of crashing:
*****************************************************************************
ALL BUILDS
IF CRASH ON BOOT - CHECK SEQUENCES
IF TITLE SCREEN LOOP - CHECK START LEVEL IN TWEAKS.INC.C
IF TEXTURES ARE MESSED UP - ALWAYS CHECK LEVEL FOG FIRST
IF ONLY ALPHA TEXTURES MESSED UP - MOVE FOG GEO LAYOUT TO LAYER 1/4 FROM 4/6
IF CRASH UPON ENTERING A LEVEL, CHECK OBJECTS. IF EDITOR, CHECK SCROLLS FIRST. IF NO OBJECTS BAD CHECK SEQUENCES
*****************************************************************************
N64 BUILD
IF SURFACE NODE POOOL OR SURFACE POOL FULL - ADD MORE TRIS TO EXT BOUNDS.H
IF CRASH ON STAR SELECT - PUSH FORWARD GODDARD SEGMENT IN SEGMENTS.H
*****************************************************************************

MORE ON AUDIO ERRORS:
On N64 build, a broken sequence will crash instantly, making it near impossible to know which sequence is broken without guessing and checking, on PC it will load just fine, but crash in the level with the broken sequence.
The easiest way to find which sequences are broken is to do a playtest on PC and then note which levels crash, replace the sequence in that level and then move on.
