COURSE_ACTS(COURSE_BOB, _(" 1 GRASSY VALLEY"),	_("BIG BOB-OMB'S BROTHER"),	_("FROM PILLAR TO PILLAR"),	_("EXTREME WALLJUMPING"),	_("DANGEROUS NARROW PATHWAY"),	_("GET SOME ORANGE COINS"),	_("HARD TO SEE COIN RINGS -WC-"))

COURSE_ACTS(COURSE_WF, _(" 2 MUSHROOM CLIFFS"),	_("THE BLACK SHROOM"),	_("DANGEROUS JUMPS"),	_("LET'S BUILD A BRIDGE"),	_("ORANGE MUSHROOM COINS"),	_("HIDDEN IN THE MOUNTAIN"),	_("FALL ONTO THE ALCOVE"))

COURSE_ACTS(COURSE_JRB, _(" 3 FOLLY BAY TOWN"),	_("ROOFTOP JUMPING FUN"),	_("MARIO THE CLIFFHANGER"),	_("THE FAR, FAR AWAY HOUSE"),	_("A JOB FOR A PLUMBER"),	_("ORANGE COINS IN TOWN"),	_("FIND THE CLOSED OFF UNDERWATER MAZE"))

COURSE_ACTS(COURSE_CCM, _(" 4 SNOW MOUNTAIN RESORT"),	_("FINDING TUXIE"),	_("TOP OF THE MOUNTAIN"),	_("ICY LAKE SURFING"),	_("WACKY SNOW HICKING"),	_("FUN IN THE SLIPPERY TUNNEL"),	_("CHIILY 8 ORANGE COINS"))

COURSE_ACTS(COURSE_BBH, _(" 5 SKYOVER FIELDS"),	_("THE CASTLE IN THE SKY"),	_("THE LOL-★ RETURNS"),	_("A VERY SMALL WAY"),	_("THE SECRET HIDEOUT"),	_("A ORANGE COIN JOURNEY"),	_("SWITCHIN' BLOCK TIME"))

COURSE_ACTS(COURSE_HMC, _(" 6 MAGMA CAVERN"),	_("BUTT-HURT ON THE LAVA"),	_("THE TOP OF THE UNDERGROUND TOWER"),	_("MELTING FLOOR SURFING"),	_("INSIDE THE DARK ROOM"),	_("ORANGE GOLD MINER"),	_("METALLIC MELTDOWN -MC-"))

COURSE_ACTS(COURSE_LLL, _(" 7 LOST, LOST WOODS"),	_("ANOTHER COLUMN STAR"),	_("UP TO THE HOUSE TOP"),	_("CLIMB THE BIG TREE"),	_("ORANGE COINS OF THE FOREST"),	_("LOST AMONG THE WOODS"),	_("BOXES OF THE TREE TOPS"))

COURSE_ACTS(COURSE_SSL, _(" 8 DRY, DRY CANYON"),	_("JUMPMAN IN THE CANYON"),	_("COINS OF THE SANDBOX"),	_("BLAST INTO THE RING"),	_("DESERTING 8 ORANGE COINS"),	_("INSIDE THE SAND TEMPLE"),	_("IS IT THE HOLY TRIFORCE? -WC-"))

COURSE_ACTS(COURSE_DDD, _(" 9 FIREY SUNSET SUMMIT"),	_("BROKEN BRIDGE LEAPING"),	_("CLIMB ATOP THE VOLCANO"),	_("FLYING TO THE HUGE CLOUD -WC-"),	_("THE SUNSET SUMMIT'S COINS"),	_("WALKING ON THE FIREY PATH -VC-"),	_("INTO THE LAVA PYRAMID"))

COURSE_ACTS(COURSE_SL, _("10 WIIHAWK'S FORT"),	_("BREAKING INTO THE FORT"),	_("AWESOME SMILEY FACE"),	_("THE UNDERWATER MAZE"),	_("THE GARDEN'S SECRET"),	_("YELLOW ORANGE COINS"),	_("THE SECRET OF TROLLESIA"))

COURSE_ACTS(COURSE_WDW, _("11 ALPHABET ATHLETIC"),	_("ATTACK OF THE WIGGLER"),	_("THE I-POINTED LETTER"),	_("WHAT IS AFTER M?"),	_("THE REAL, REAL LOL-★"),	_("ORANGE COINS OF ANYTHING"),	_("THE THING YOU ALMOST CAN'T SEE -WC-"))

COURSE_ACTS(COURSE_TTM, _("12 RAINBOW SPACE GALAXY"),	_("THE BIG STAR RAMPAGE"),	_("SHOOTING THROUGH SPACE"),	_("HOT CAVE EXPLORATION -MC-"),	_("ORANGE COINS OF THE GALAXY"),	_("TOP OF THE GALAXY"),	_("HIDDEN STAR OF THE GALAXY -WC-"))

COURSE_ACTS(COURSE_THI, _("13 ..."),	_("PLUCK THE PIRANHA FLOWER"),	_("THE TIP TOP OF THE HUGE ISLAND"),	_("REMATCH WITH KOOPA THE QUICK"),	_("FIVE ITTY BITTY SECRETS"),	_("WIGGLER'S RED COINS"),	_("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 MADE BY BRODUTE"),	_("ROLL INTO THE CAGE"),	_("THE PIT AND THE PENDULUMS"),	_("GET A HAND"),	_("STOMP ON THE THWOMP"),	_("TIMED JUMPS ON MOVING BARS"),	_("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("   ???"),	_("JUST GET THE STAR"),	_("IT'S THE SAME THING!"),	_("COINS AMASSED IN A MAZE"),	_("SWINGIN' IN THE BREEZE"),	_("TRICKY TRIANGLES!"),	_("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(15, _("   FIERY CRATER RUINS"))
SECRET_STAR(16, _("   ICY PYRAMID DESERT"))
SECRET_STAR(17, _("   BIG ZTAR GALAXY"))
SECRET_STAR(18, _("   CHILLY SUMMIT SLIDE"))
SECRET_STAR(19, _("   METAL CAP IN THE TOXIC FACTORY"))
SECRET_STAR(20, _("   WING CAP IN THE TOWER"))
SECRET_STAR(21, _("   VANISH CAP IN THE LOST MAZE"))
SECRET_STAR(22, _("   NOSTALGIC RETRO WORLD"))
SECRET_STAR(23, _("   WEEGEE'S CHALLENGE"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   TOTAL SECRET STARS"))
EXTRA_TEXT(0,_("YAY! SECRET STAR GET!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
