COURSE_ACTS(COURSE_BOB, _(" 1 ETERNAL DREAM ENTRANCE"),	_("DOREMY'S FLAMMABLE ENVOY"),	_("CROSSOVER-WALLKICKS LESSON"),	_("ARCH-WALLKICKS LESSON"),	_("TOP OF THE BLUE SKY"),	_("MORE COLLECTABLE OBJECT"),	_("ETERNAL SPRING DREAM"))

COURSE_ACTS(COURSE_WF, _(" 2 SCRAMBLED SCAMPER"),	_("REPTYL'S ANIMAL TRAIL"),	_("THE MODEST MEPHISTO MAZE"),	_("MAGICTOWER OF THE DOMAIN"),	_("POSSESSOR OF THE MOUNTAIN"),	_("RED SUFFER"),	_("STAR SHOWER SURFER"))

COURSE_ACTS(COURSE_JRB, _(" 3 WHOMP'S VENGEANCE"),	_("PREPARING BOARDING"),	_("TOP OF THE BATTLESHIP"),	_("THE 3RD BATTLE"),	_("SMALL QUICKSAND SHIP"),	_("SCATTERED FLIPSWITCHES"),	_("RED COINS IN RAVINE"))

COURSE_ACTS(COURSE_CCM, _(" 4 WINTER MELTING LAND"),	_("TOP OF THE ICE-AGE SAVANNA"),	_("NEW BIRD'S NEST"),	_("69TH BAR CRISIS"),	_("GLACIAL RED COINS"),	_("FRAPPE FLIPSWITCHES"),	_("KING BOB-OMB'S FOOD RESERVES"))

COURSE_ACTS(COURSE_BBH, _(" 5 SKY STAIRWAY STEPS"),	_("MORE INTENSE TREASURE"),	_("STEPPING SUBVERSIVE PILLARS"),	_("THE CLIMBLING CASTLE 2"),	_("INHABITANTS OF SKY STREET"),	_("SECOND CHAIN CRISIS"),	_("EXPLICIT TROLL TREASURES"))

COURSE_ACTS(COURSE_HMC, _(" 6 PLAGUING PLANETS"),	_("OVER THE DIAMONDS"),	_("WOODEN BRIDGE ROAD"),	_("PAST LAST SECRET"),	_("NEW SECRET POINTS AT RANDOM"),	_("CENTRIFUGAL CUP JUMPS"),	_("BON LUMPS VOYAGE !"))

COURSE_ACTS(COURSE_LLL, _(" 7 LOST MEMORIES"),	_("TSUCNENT'S RUINS"),	_("LOST LUMP"),	_("CROSSED-OVER CLOCKHANDS"),	_("SWITCHLESS STEM"),	_("BRAMBLE TSUCRAMBLE"),	_("REMNANT OF TT REDS"))

COURSE_ACTS(COURSE_SSL, _(" 8 BEGINNING THE TRAGEDY"),	_("STARTING A NIGHTMARE"),	_("RIVERSIDE CLIFFS"),	_("THE OBVIOUS SOLUTION OF QUICKSAND"),	_("REPEATED 72 WALL-KICKS"),	_("THE DEEPEST IN THE FIRST TRAGEDY"),	_("FIRST MEETING OF THE 2ND ROUND"))

COURSE_ACTS(COURSE_DDD, _(" 9 SUBTERRANEAN CITY FLAME"),	_("FLAME FOUR SUBURB"),	_("TSUCFACE REDANCE"),	_("STAR'S NUCLEUS CAPITAL"),	_("STAR'S NUCLEUS CAPITAL II"),	_("BOTTOMLESS CRADLE"),	_("VENGEFUL RED SPIRIT'S ERRATIC STEP"))

COURSE_ACTS(COURSE_SL, _("10 JOY OR SORROW"),	_("PLOCKED SCHOOL ROUTE"),	_("ACRYLIC GRAY TOWER"),	_("DISCOLORED COTTON CAPE"),	_("TSUCNENT BROTHERS"),	_("INVITATION OF THE ANCIENT CASTLE"),	_("RED AMULETS IN LEGACY ISLAND"))

COURSE_ACTS(COURSE_WDW, _("11 CUBIC PHOBIC"),	_("WHOMP'S LOST ARTICLE"),	_("MARCH ON BURNT QUICKSAND"),	_("CUBIC CASTLE COLLAPSE"),	_("TOPS OF THE THUNDER FORTRESS"),	_("PARALLEL TRAGEDY"),	_("CLOSED SKY CAGE"))

COURSE_ACTS(COURSE_TTM, _("12 WALL WALL MELANCHOLY"),	_("CONTRASTING COMPLEX"),	_("MAGNITUDE OBSESSION"),	_("PRECIPITOUS DISTRESS"),	_("JEALOUSY OF 91"),	_("ENCOURAGEMENT FROM MY BEST FRIEND"),	_("DETOUR TO TRAUMATIC TRAGEDY"))

COURSE_ACTS(COURSE_THI, _("13 MY FIRST DETERMINATION"),	_("TOXIC TENNIS STADIUM"),	_("FIRST MEETING WITH INVISIBLE WALLKICKS"),	_("SECOND INVISIBLE GRAPHITE"),	_("THE GRILL CONSTRUCTION"),	_("THE ENTRANCE TO LAND OF FANTASY"),	_("PERMANENT SKY BATTLE"))

COURSE_ACTS(COURSE_TTC, _("14 BONDS TOWARD THE FUTURE"),	_("SKY HIGH CASTLE OF KOOPA"),	_("A STAR OF HOPE IN THE BLUE SKY"),	_("HUGE SATELLITE IN CLOSED GARDEN"),	_("SKY HIGH RED GLORY GOAL"),	_("SKY HIGH YELLOW CASTLE DREAM EDITION"),	_("DISCOLORED SKY CASTLES"))

COURSE_ACTS(COURSE_RR, _("15 FINAL TRAGEDY"),	_("SHINE STAR IN THE PARADISE"),	_("HEXAGONS MADNESS"),	_("PURPLE NEEDLES OF PAINFUL REPROACH"),	_("WALLKICK EXHIBITION"),	_("TSUCFACE'S HAVEN"),	_("CLIMAX OF THE CRAPPY DREAM"))

SECRET_STAR(15, _("   BOWSER'S SOLEMN RUIN"))
SECRET_STAR(16, _("   BOWSER'S LOST RUIN"))
SECRET_STAR(17, _("   BOWSER'S DREAMY PROMENADE"))
SECRET_STAR(18, _("   LOCKED DREAM"))
SECRET_STAR(19, _("   MADNIGHT MEMORIES"))
SECRET_STAR(20, _("   CANYON MEMORIES"))
SECRET_STAR(21, _("   DEPARTURE MEMORIES"))
SECRET_STAR(22, _("   TSUCNENT'S DAWN"))
SECRET_STAR(23, _("   EVERLASTING ENCORE"))
SECRET_STAR(24, _("   RAMBI'S REVERIE"))
CASTLE_SECRET_STARS(_("   A HIDDEN STAR"))
EXTRA_TEXT(0,_("ONE OF THE TREASURE STARS!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
