COURSE_ACTS(COURSE_BOB, _(" 1 DEVIL'S DICE"),	_("LITTLE WARM-UP"),	_("LET'S-A-GO!"),	_("SCALE THE TOWER"),	_("FUNDAMENTAL TUNNEL PROBLEMS"),	_("FIRST RED KATASTROPHE"),	_("YOU WON'T FIND ME!"))

COURSE_ACTS(COURSE_WF, _(" 2 VIRUSVINE VERANDA"),	_("THE VINE'S TREASURE"),	_("TIME PRESSURE TRAVEL"),	_("ON TOP OF THAT WALL!"),	_("JUMPING-PARCOUR 1"),	_("JUMPING-PARCOUR 2"),	_("LIGHT RED COINS"))

COURSE_ACTS(COURSE_JRB, _(" 3 DEEPRED DEPTHS"),	_("THE UPPER END OF THE CRATER"),	_("SMALL PILLAR TRAINING"),	_("HOT STEP STONES"),	_("DEEP WITHIN THE VOLCANO"),	_("ARTISTIC COIN SEARCH"),	_("PAINFUL EXPERIENCE"))

COURSE_ACTS(COURSE_CCM, _(" 4 SYSTEM OF A DOWNTOWN"),	_("GHOST ODYSSEE"),	_("GUARDIAN OF THE VILLAGE"),	_("EXPANDED SECRET ROOM"),	_("DEATH PIT"),	_("SO CLOSE AND YET SO FAR AWAY"),	_("HIDDEN COWARD"))

COURSE_ACTS(COURSE_BBH, _(" 5 DROWNED FACTORY"),	_("PEARL DIVER"),	_("THE TUNNEL LABYRINTH PART 1"),	_("THE TUNNEL LABYRINTH PART 2"),	_("THE TUNNEL LABYRINTH PART 3"),	_("THE TUNNEL LABYRINTH PART 4"),	_("THE TUNNEL LABYRINTH PART 5"))

COURSE_ACTS(COURSE_HMC, _(" 6 INFERNOPIT CAVE"),	_("DEEP WITHIN THE CALDRON"),	_("BALLS OF STEEL AND FIRE"),	_("BLUE CONTRAST BLOCKS"),	_("SIDE CALDRON SHENANIGANS"),	_("DANCE WITH THE HEAVE-HOS"),	_("RED SIN"))

COURSE_ACTS(COURSE_LLL, _(" 7 MELTING ICECRYSTAL-TOWER"),	_("BRICK BATTLE"),	_("FLOATATION IN BLOCK FORM"),	_("SOUL OF A CLIMBER"),	_("BLOOR-RED FINANCES"),	_("ANNOYING SEARCH"),	_("UNJUSTIFIABLE SEARCH"))

COURSE_ACTS(COURSE_SSL, _(" 8 OVERGROWN OASIS"),	_("STILL UNDER CONSTRUCTION"),	_("FLOOD LANDING STAGE"),	_("NOT SO SECRET SECRET ANYMORE"),	_("DOUBTFUL PYRAMID"),	_("HIDDEN HERMIT"),	_("YOU SHALL DROWN!"))

COURSE_ACTS(COURSE_DDD, _(" 9 FIREFLOWER FIELDS"),	_("ANOTHER REMATCH WITH KING BOB-OMB"),	_("WINDY MILL"),	_("WAY TOO EASY COINS"),	_("THE UNSTABLE WOODEN CONSTRUCTION"),	_("NOT SO SECRET CAVERN"),	_("BARK BEETLE JUMPS"))

COURSE_ACTS(COURSE_SL, _("10 BREEZING BEACH"),	_("SECRET OF THE SMARAGDS"),	_("HOT POLE-DANCE"),	_("SOMEWHERE IN THE NOWHERE"),	_("NOWHERE IN THE SOMEWHERE"),	_("COLD TOMB"),	_("HEMOGLOBIN-COINS"))

COURSE_ACTS(COURSE_WDW, _("11 DRIED-OUT DEAD DESERT"),	_("BURNING FEET"),	_("AIRY STORED COINS"),	_("THE OLD HIDEOUT"),	_("GRAVE DIGGER"),	_("CEMETARY ARTISTICS"),	_("THE SAND PLATEAU'S TORTURE"))

COURSE_ACTS(COURSE_TTM, _("12 CLIFF OF PAIN"),	_("MOVE YOUR BUTT UP THERE!"),	_("WAY TOO HIGH"),	_("ANOTHER PROBLEMATIC BOX"),	_("HEAVE-HO CAVE"),	_("YOU-CAN-GUESS-WHICH COINS"),	_("BRAZENLY PLACED"))

COURSE_ACTS(COURSE_THI, _("13 ACID PEAKS"),	_("WELCOME TO THE ACID SWAMP"),	_("EYE TO EYE"),	_("ACIDPROOF BOXES"),	_("IN THE BIG CAVE"),	_("ANOTHER CLIMBING CHALLENGE"),	_("LAVA-COLORED GLITTER"))

COURSE_ACTS(COURSE_TTC, _("14 VENENO SPHERE"),	_("THE SAME PLACE IN A WORSE WORLD"),	_("THROUGH THE HEART OF THE WORLD"),	_("THE EDGE OF THE WORLD"),	_("THE ROOF OF THE WORLD"),	_("WORLDWIDE PAIN"),	_("BLOODRED COINS OF RUINATION"))

COURSE_ACTS(COURSE_RR, _("15 CRUDELO SPHERE"),	_("THE NIGHTMARE BEGINS"),	_("JUST GO CRAZY"),	_("STRAIGHT FROM HELL"),	_("TRAUMATISING EXPERIENCE"),	_("MORBID DEADLY PUZZLE"),	_("BLOODY SCREAM OF RAGE"))

SECRET_STAR(15, _("   BOWSER'S BEAUTIFUL BACKYARD"))
SECRET_STAR(16, _("   BOWSER'S QUICKSAND PIT"))
SECRET_STAR(17, _("   ZTAR ZANCTUARY"))
SECRET_STAR(18, _("   OLD SUPPLY SLIDE"))
SECRET_STAR(19, _("   TOXIC TERRACE"))
SECRET_STAR(20, _("   DEVIL'S PIT"))
SECRET_STAR(21, _("   DUST DESTINATION"))
SECRET_STAR(22, _("   LAKE OF THE LORDS"))
SECRET_STAR(23, _("   TRIARC-BRIDGE"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   BONUSSTARS"))
EXTRA_TEXT(0,_("BONUS STAR"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
