COURSE_ACTS(COURSE_BOB, _(" 1 DICE-FORTRESS"),	_("WALLJUMPING LESSON"),	_("CONQUER THE PILLARS"),	_("THE OBSERVATION TOWER"),	_("COLLECT 8 RED COINS"),	_("SECRETS OF THE SKY"),	_("THE BOX'S TREASURE"))

COURSE_ACTS(COURSE_WF, _(" 2 SKYWARD SLOPES"),	_("TO THE TOP OF THE TOWER"),	_("8 DANGEROUS RED COINS"),	_("THE OUTER WALL"),	_("NO TIME TO WASTE"),	_("FLOATATION TECHNOLOGY BOX"),	_("MASTER OF JUMPING"))

COURSE_ACTS(COURSE_JRB, _(" 3 AZURE-ABYSS"),	_("THE DEEPEST DIVE"),	_("CAVE EXPLORATION"),	_("PRECISION PILLARS"),	_("RED TREASURE HUNT"),	_("HEAVY METAL REQUIRED"),	_("WALL OF FAILURE?"))

COURSE_ACTS(COURSE_CCM, _(" 4 SYSTEM OF A TOWN"),	_("ROOFTOP CLIMBING"),	_("INTO THE SEWER SYSTEM"),	_("THE SECONDARY HOUSE ENTRANCE"),	_("FIND THE SECRET ROOM"),	_("THE VILLAGE'S RED COINS"),	_("THE MANSION'S SECRET STAR"))

COURSE_ACTS(COURSE_BBH, _(" 5 HAUNTED FACTORY"),	_("EXPLORE THE FACTORY"),	_("TOXIC RIDE"),	_("WATCH YOUR STEP"),	_("BLOCKS OF DOOM"),	_("8 SPOOKY RED COINS"),	_("THE HIDDEN ROOM"))

COURSE_ACTS(COURSE_HMC, _(" 6 STALAGMITE CAVE"),	_("DOWNWARDS"),	_("BURNING-HOT TUNNEL"),	_("RED COINS IN THE CAVERN"),	_("HOT OBSTACLE COURSE"),	_("CHUCKYA'S CHALLENGE"),	_("CAP-COMBINATION"))

COURSE_ACTS(COURSE_LLL, _(" 7 ICE CRYSTAL-TOWER"),	_("REMATCH WITH KING WHOMP"),	_("SCALDING WATERS"),	_("ALMOST TO THE TOP"),	_("FROZEN RED COINS"),	_("HOW HIGH CAN YOU GO?"),	_("DOWN-LOW SECRET STAR"))

COURSE_ACTS(COURSE_SSL, _(" 8 OVERHEATING OASIS"),	_("UNDER CONSTRUCTION"),	_("HIDDEN INSIDE THE LABYRINTH"),	_("THE PYRAMIDS OF TUTANPOKEY"),	_("THUNDER MOUNTAIN"),	_("8 HOT RED COINS"),	_("THE PHARAOH'S SANDY SECRET"))

COURSE_ACTS(COURSE_DDD, _(" 9 FLOWERY GARDENS"),	_("KING BOB-OMB'S REVENGE"),	_("RED COINS IN THE GARDENS"),	_("VAST WOODEN STRUCTURE"),	_("LUMBERJACK JUMPING"),	_("THE WINDMILL'S STAR"),	_("A HIDDEN CAVE"))

COURSE_ACTS(COURSE_SL, _("10 SWAMPY SPRING"),	_("KOOPA THE CHEATER"),	_("GROUNDED RED COINS"),	_("THE TOWER OF POWER"),	_("THE OTHER POWER-TOWER"),	_("FEARFUL FAILURE BLOCKS"),	_("A CLIFF'S HIDDEN STAR"))

COURSE_ACTS(COURSE_WDW, _("11 SUNNY BEACH"),	_("MYSTERY OF THE SAPPHIRES"),	_("GOLDEN GLIMMER"),	_("THING WITH SPIKES"),	_("TREASURE HUNT"),	_("SHINY OBJECT"),	_("STARLIGHT"))

COURSE_ACTS(COURSE_TTM, _("12 CLIFF OF WRATH"),	_("KING BOO'S INVASION"),	_("TRICKY PILLARS"),	_("RED COIN QUEST"),	_("WALLJUMPING MADNESS"),	_("PROBLEMATIC BOX"),	_("LOOK OUT"))

COURSE_ACTS(COURSE_THI, _("13 MOLTEN TREASURE CHEST"),	_("HIGH IN THE SKY"),	_("RED COIN FLIGHT"),	_("INSIDE A CAVE"),	_("THE MOUNTAIN PEAKS"),	_("HOT AND SPICY"),	_("ACROBATIC FLYER"))

COURSE_ACTS(COURSE_TTC, _("14 LUMINIUM-SPHERE"),	_("TOWER OF THE WEST"),	_("JUMPING MAESTRO"),	_("BOTTOMLESS FORTRESS"),	_("BEHIND THE WALL"),	_("TREASURE-TOWER"),	_("RED FRUSTRATION"))

COURSE_ACTS(COURSE_RR, _("15 OMBRU-SPHERE"),	_("THE SAME PLACE AGAIN?"),	_("TINY TOWER"),	_("THE HIGH BUILDING"),	_("INTENSE CHALLENGE"),	_("FLIGHT FOR SIGHT"),	_("MORE RED FRUSTRATION"))

SECRET_STAR(15, _("   BOWSER'S BADLANDS-BATTLEFIELD"))
SECRET_STAR(16, _("   BOWSER'S AQUATIC CASTLE"))
SECRET_STAR(17, _("   BOWSER'S CRYSTAL PALACE"))
SECRET_STAR(18, _("   FROZEN SLIDE"))
SECRET_STAR(19, _("   TOXIC-SWITCH OF DANGER"))
SECRET_STAR(20, _("   LAVA-SWITCH OF ERUPTION"))
SECRET_STAR(21, _("   DUST-SWITCH OF IDENTITY"))
SECRET_STAR(22, _("   TOWER OF THE EAST"))
SECRET_STAR(23, _("   CHAMPION'S CHALLENGE"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   BONUS STARS"))
EXTRA_TEXT(0,_("YOU GOT A BONUS STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
