const GeoLayout marios_winged_metal_cap_geo[]= {
GEO_SHADOW(0,180,75),
GEO_OPEN_NODE(),
GEO_SCALE(0,16384),
GEO_OPEN_NODE(),
GEO_ASM(10, geo_update_layer_transparency),
GEO_SWITCH_CASE(2, geo_switch_anim_state),
GEO_OPEN_NODE(),
GEO_NODE_START(),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(1,DL_marios_winged_metal_cap_geo_0x3022ff8),
GEO_DISPLAY_LIST(4,DL_marios_winged_metal_cap_geo_0x3023108),
GEO_CLOSE_NODE(),
GEO_NODE_START(),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(5,DL_marios_winged_metal_cap_geo_0x3023298),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
const GeoLayout marios_metal_cap_geo[]= {
GEO_SHADOW(0,180,75),
GEO_OPEN_NODE(),
GEO_SCALE(0,16384),
GEO_OPEN_NODE(),
GEO_ASM(10, geo_update_layer_transparency),
GEO_SWITCH_CASE(2, geo_switch_anim_state),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(1,DL_marios_winged_metal_cap_geo_0x3022ff8),
GEO_DISPLAY_LIST(1,DL_marios_winged_metal_cap_geo_0x3022ff8),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
const GeoLayout marios_wing_cap_geo[]= {
GEO_SHADOW(0,180,75),
GEO_OPEN_NODE(),
GEO_SCALE(0,16384),
GEO_OPEN_NODE(),
GEO_ASM(10, geo_update_layer_transparency),
GEO_SWITCH_CASE(2, geo_switch_anim_state),
GEO_OPEN_NODE(),
GEO_NODE_START(),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(1,DL_marios_wing_cap_geo_0x3022f48),
GEO_DISPLAY_LIST(4,DL_marios_wing_cap_geo_0x30230b0),
GEO_CLOSE_NODE(),
GEO_NODE_START(),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(5,DL_marios_wing_cap_geo_0x3023160),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
const GeoLayout marios_cap_geo[]= {
GEO_SHADOW(0,180,75),
GEO_OPEN_NODE(),
GEO_SCALE(0,16384),
GEO_OPEN_NODE(),
GEO_ASM(10, geo_update_layer_transparency),
GEO_SWITCH_CASE(2, geo_switch_anim_state),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(1,DL_marios_wing_cap_geo_0x3022f48),
GEO_DISPLAY_LIST(1,DL_marios_wing_cap_geo_0x3022f48),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
